In [2]:
import numpy as np
import os
from PIL import Image

In [3]:
path = "Dataset/"
arr = os.listdir( path )
#print(arr)
for f in arr:
    if f.endswith(".JPEG"):
        img = Image.open(path + f)
        data = np.asarray(img)
        #print(data)

[[[235 229 231]
  [237 233 234]
  [238 233 239]
  ..., 
  [236 235 240]
  [248 249 251]
  [222 223 225]]

 [[238 234 235]
  [238 236 237]
  [237 235 240]
  ..., 
  [224 223 228]
  [227 227 229]
  [213 213 215]]

 [[222 220 221]
  [232 230 231]
  [232 232 234]
  ..., 
  [226 225 230]
  [222 222 224]
  [216 216 218]]

 ..., 
 [[ 30  29  43]
  [ 28  28  40]
  [ 26  26  38]
  ..., 
  [ 64  64  76]
  [ 54  54  62]
  [ 16  17  22]]

 [[ 27  26  40]
  [ 25  24  38]
  [ 25  24  38]
  ..., 
  [ 55  54  68]
  [ 65  65  75]
  [ 27  27  35]]

 [[ 23  22  38]
  [ 24  23  37]
  [ 25  24  38]
  ..., 
  [ 48  45  62]
  [ 63  63  75]
  [ 55  55  65]]]
[[[15 17 12]
  [17 19 14]
  [18 21 14]
  ..., 
  [54 54 44]
  [49 49 39]
  [43 43 33]]

 [[16 18 13]
  [18 21 14]
  [19 22 15]
  ..., 
  [47 47 37]
  [48 48 38]
  [50 50 40]]

 [[17 20 13]
  [19 22 15]
  [21 24 15]
  ..., 
  [43 43 33]
  [46 48 37]
  [53 55 44]]

 ..., 
 [[49 49 47]
  [50 50 48]
  [52 52 50]
  ..., 
  [22 21 17]
  [21 20 16]
  [18 17 13]]

  [141 140 135]]]
[[[115 120 123]
  [130 131 135]
  [127 122 126]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[117 110 117]
  [125 114 122]
  [ 98  83  90]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[200 193 200]
  [218 209 214]
  [222 209 216]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..., 
  [ 19  15  16]
  [ 23  23  23]
  [ 20  22  21]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..., 
  [  3   1   2]
  [ 16  16  16]
  [ 23  23  23]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..., 
  [  9   9   9]
  [ 12  12  12]
  [  7   7   7]]]
[[[ 94  68  31]
  [ 93  69  33]
  [ 89  67  28]
  ..., 
  [128 124  89]
  [130 124  90]
  [130 121  88]]

 [[ 97  71  34]
  [ 95  71  33]
  [ 89  67  28]
  ..., 
  [128 122  86]
  [131 125  89]
  [130 122  86]]

 [[ 90  67  26]
  [ 89  65  27]
  [ 93  67  30]
  ..., 
  [126 121  83]
  [130 125  87]
  [129 121  84]]

 ..., 
 [[ 80  74  40

[[[132 143 139]
  [132 142 141]
  [133 142 141]
  ..., 
  [205 195 170]
  [207 196 166]
  [209 194 161]]

 [[131 142 136]
  [133 142 139]
  [133 142 139]
  ..., 
  [204 195 166]
  [219 205 178]
  [208 192 166]]

 [[131 142 136]
  [133 142 137]
  [135 141 139]
  ..., 
  [218 207 179]
  [226 211 188]
  [207 190 172]]

 ..., 
 [[200 194 172]
  [197 191 169]
  [198 192 168]
  ..., 
  [153 147 115]
  [147 141 107]
  [153 145 109]]

 [[201 200 172]
  [203 198 176]
  [200 193 175]
  ..., 
  [155 150 121]
  [146 141 111]
  [134 129  97]]

 [[200 199 171]
  [203 198 176]
  [202 194 175]
  ..., 
  [141 136 107]
  [145 140 110]
  [143 138 106]]]
[[[213 209 109]
  [212 208 108]
  [211 207 107]
  ..., 
  [125 110  55]
  [126 111  54]
  [139 124  69]]

 [[212 208 108]
  [212 208 108]
  [211 207 107]
  ..., 
  [138 123  66]
  [139 124  65]
  [146 131  74]]

 [[211 207 107]
  [211 207 107]
  [211 207 107]
  ..., 
  [150 136  75]
  [151 137  74]
  [152 138  77]]

 ..., 
 [[218 198 174]
  [217 197 173]


[[[248 249 251]
  [244 245 247]
  [254 255 255]
  ..., 
  [253 253 253]
  [253 253 255]
  [236 234 237]]

 [[254 255 255]
  [249 251 250]
  [251 253 252]
  ..., 
  [238 240 237]
  [253 255 254]
  [229 230 232]]

 [[251 255 252]
  [242 247 243]
  [240 242 239]
  ..., 
  [233 238 231]
  [249 254 250]
  [228 232 231]]

 ..., 
 [[ 32  70  91]
  [ 32  68  92]
  [ 29  64  92]
  ..., 
  [  8  29  60]
  [  9  26  56]
  [ 13  38  60]]

 [[ 33  71  92]
  [ 37  74 100]
  [  4  39  69]
  ..., 
  [  5  24  54]
  [  0  14  43]
  [ 11  33  54]]

 [[ 32  73  93]
  [ 19  59  84]
  [  4  41  70]
  ..., 
  [ 17  37  64]
  [  0  16  42]
  [  8  29  48]]]
[[[253 255 254]
  [253 255 254]
  [253 255 254]
  ..., 
  [231 236 239]
  [230 235 238]
  [230 235 238]]

 [[253 255 254]
  [253 255 254]
  [253 255 254]
  ..., 
  [229 237 240]
  [230 235 239]
  [230 235 239]]

 [[253 255 254]
  [253 255 254]
  [253 255 254]
  ..., 
  [229 237 240]
  [230 235 239]
  [230 235 239]]

 ..., 
 [[ 90  88  76]
  [ 90  88  76]


[[[164 148 132]
  [102  90  78]
  [108  98  73]
  ..., 
  [149 142 126]
  [118 104  93]
  [131 137 123]]

 [[142 127 108]
  [108 107  86]
  [100  82  60]
  ..., 
  [ 94  87  71]
  [118 111  95]
  [ 95  77  67]]

 [[101  81  57]
  [ 95  92  57]
  [124 102  79]
  ..., 
  [106  79  62]
  [ 88  77  59]
  [112 103  88]]

 ..., 
 [[ 70  73  82]
  [ 98  98  96]
  [ 74  97  77]
  ..., 
  [150 150 124]
  [161 158 141]
  [162 147 126]]

 [[ 69  76  82]
  [100  99 104]
  [ 99 118 114]
  ..., 
  [157 152 130]
  [168 166 143]
  [161 148 116]]

 [[ 71  79  81]
  [100  98 103]
  [122 135 141]
  ..., 
  [149 145 118]
  [157 158 124]
  [152 146  96]]]
[[[112 237 255]
  [108 240 253]
  [108 240 252]
  ..., 
  [162 176 203]
  [170 184 211]
  [170 184 213]]

 [[114 237 255]
  [110 240 254]
  [113 241 254]
  ..., 
  [169 183 210]
  [175 189 216]
  [178 192 219]]

 [[112 239 254]
  [108 242 253]
  [109 241 253]
  ..., 
  [164 180 205]
  [178 194 219]
  [169 183 210]]

 ..., 
 [[ 56  83  92]
  [ 57  81  91]


[[[ 68  82  59]
  [ 70  78  57]
  [ 66  76  52]
  ..., 
  [ 97 106  87]
  [ 95 104  83]
  [ 98 107  86]]

 [[ 69  78  57]
  [ 65  77  55]
  [ 74  82  61]
  ..., 
  [ 96 105  84]
  [ 97 106  85]
  [ 92 101  80]]

 [[ 73  82  61]
  [ 66  78  56]
  [ 75  83  62]
  ..., 
  [ 97 104  86]
  [ 98 107  88]
  [ 99 110  93]]

 ..., 
 [[ 92  71  42]
  [ 96  71  51]
  [ 98  71  50]
  ..., 
  [104  87  67]
  [108  90  70]
  [110  89  72]]

 [[ 93  72  43]
  [ 95  70  48]
  [ 96  71  49]
  ..., 
  [ 98  90  67]
  [101  90  68]
  [102  89  70]]

 [[ 91  67  39]
  [ 94  69  47]
  [ 96  71  49]
  ..., 
  [106  88  68]
  [106  85  66]
  [107  86  67]]]
[[[156 143 135]
  [200 187 178]
  [186 174 160]
  ..., 
  [169 161 150]
  [171 163 152]
  [152 144 133]]

 [[191 178 169]
  [197 185 173]
  [181 169 155]
  ..., 
  [170 161 152]
  [176 167 160]
  [154 145 140]]

 [[183 171 159]
  [186 174 160]
  [186 174 158]
  ..., 
  [174 165 158]
  [164 154 152]
  [146 136 137]]

 ..., 
 [[185 181 198]
  [195 191 206]


[[[221 223 210]
  [223 223 211]
  [226 224 212]
  ..., 
  [230 230 230]
  [231 231 231]
  [231 231 231]]

 [[220 222 209]
  [225 225 213]
  [228 226 214]
  ..., 
  [228 228 228]
  [229 229 229]
  [229 229 229]]

 [[223 225 212]
  [225 225 213]
  [226 226 214]
  ..., 
  [228 228 228]
  [229 229 227]
  [229 229 227]]

 ..., 
 [[146  25  32]
  [144  30  29]
  [142  28  27]
  ..., 
  [155  28  35]
  [167  32  36]
  [179  39  40]]

 [[149  28  33]
  [144  29  26]
  [141  28  24]
  ..., 
  [152  25  32]
  [167  32  36]
  [179  39  40]]

 [[152  29  34]
  [144  29  26]
  [141  28  24]
  ..., 
  [153  27  31]
  [169  35  36]
  [179  39  38]]]
[[[188 157 111]
  [187 159 112]
  [189 162 115]
  ..., 
  [169 145  99]
  [175 148 101]
  [176 148 101]]

 [[193 162 116]
  [190 161 121]
  [190 163 116]
  ..., 
  [171 144  99]
  [175 147 100]
  [172 144  97]]

 [[190 162 115]
  [187 157 121]
  [192 163 119]
  ..., 
  [176 147 103]
  [177 149 102]
  [176 148 101]]

 ..., 
 [[102  70  49]
  [ 89  52  33]


[[[15 12  7]
  [13 12  7]
  [13 12  7]
  ..., 
  [ 4  4  4]
  [ 4  4  4]
  [ 3  3  3]]

 [[12 11  6]
  [14 13  8]
  [13 12  7]
  ..., 
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[11 10  5]
  [15 14  9]
  [12 11  6]
  ..., 
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 ..., 
 [[ 5  5  3]
  [ 6  6  4]
  [ 6  6  4]
  ..., 
  [12  8  5]
  [13  9  8]
  [11  7  6]]

 [[ 5  5  3]
  [ 5  5  3]
  [ 6  6  4]
  ..., 
  [11  7  4]
  [12  8  7]
  [11  7  6]]

 [[ 3  3  1]
  [ 4  4  2]
  [ 4  4  2]
  ..., 
  [11  7  4]
  [12  8  7]
  [11  7  6]]]
[[[255 255 255]
  [245 245 245]
  [249 249 249]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 252 252]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [254 254 254]
  [242 242 242]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[147   4  34]
  [148   9  28]
  [151   9  31]
  ..., 
  [211  33  69]
  [219  24  58]
  [229  42  73]]

 [[148  10  36]
  [150  11  30]
  

[[[197 162 132]
  [197 162 132]
  [198 161 132]
  ..., 
  [243 238 232]
  [243 238 232]
  [243 238 232]]

 [[190 157 126]
  [193 158 128]
  [197 162 132]
  ..., 
  [243 238 232]
  [243 238 232]
  [243 238 232]]

 [[199 166 135]
  [185 152 121]
  [181 148 117]
  ..., 
  [243 238 232]
  [243 238 232]
  [243 238 232]]

 ..., 
 [[112  82  46]
  [ 93  64  30]
  [ 38  11   0]
  ..., 
  [246 234 222]
  [246 234 222]
  [246 234 222]]

 [[127  89  52]
  [121  85  49]
  [103  70  39]
  ..., 
  [246 234 222]
  [246 234 222]
  [246 234 222]]

 [[117  75  37]
  [120  80  44]
  [119  83  51]
  ..., 
  [246 234 222]
  [246 234 222]
  [246 234 222]]]
[[[ 3  3  5]
  [ 3  3  5]
  [ 3  3  5]
  ..., 
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  1]]

 [[ 4  4  6]
  [ 4  4  6]
  [ 4  4  6]
  ..., 
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 4  4  6]
  [ 4  4  6]
  [ 4  4  6]
  ..., 
  [ 2  2  4]
  [ 3  3  5]
  [ 2  2  2]]

 ..., 
 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ..., 
  [42 39 30]
  [35 32 23]
  [32 29 20]]

[[[59 66 74]
  [51 60 67]
  [44 53 60]
  ..., 
  [56 59 40]
  [57 60 41]
  [59 62 43]]

 [[43 50 56]
  [39 48 53]
  [37 46 51]
  ..., 
  [54 58 35]
  [55 59 36]
  [57 61 38]]

 [[36 43 49]
  [37 44 50]
  [37 46 51]
  ..., 
  [54 58 31]
  [55 59 32]
  [56 60 33]]

 ..., 
 [[51 49 62]
  [55 51 65]
  [60 56 70]
  ..., 
  [22 23 28]
  [22 23 28]
  [21 22 26]]

 [[50 47 58]
  [51 48 59]
  [54 51 62]
  ..., 
  [21 22 27]
  [20 21 26]
  [20 21 26]]

 [[53 50 61]
  [51 48 59]
  [49 46 55]
  ..., 
  [21 22 27]
  [20 21 26]
  [19 20 25]]]
[[[  0   0 101]
  [ 17  16 118]
  [  0   0  87]
  ..., 
  [  0   0  87]
  [ 11  13  98]
  [  0   0 136]]

 [[ 17  16 118]
  [ 52  49 140]
  [ 33  28 110]
  ..., 
  [115 122 150]
  [119 126 154]
  [ 23  18 118]]

 [[  0   0  86]
  [ 35  27 110]
  [ 12   2  73]
  ..., 
  [ 93 100 110]
  [127 134 144]
  [  0   0  71]]

 ..., 
 [[254 254 254]
  [ 66  66  66]
  [204 204 204]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[253 253 253]
  [219 219 219]
  

[[[192 177 144]
  [189 174 141]
  [187 172 139]
  ..., 
  [165 157 136]
  [162 155 136]
  [172 165 147]]

 [[193 178 145]
  [193 178 145]
  [187 172 139]
  ..., 
  [162 156 134]
  [157 150 131]
  [164 157 138]]

 [[185 170 137]
  [188 173 140]
  [187 172 139]
  ..., 
  [158 152 130]
  [161 155 133]
  [168 162 140]]

 ..., 
 [[ 78  68  66]
  [ 89  79  77]
  [ 86  75  73]
  ..., 
  [ 68  57  55]
  [ 65  53  53]
  [ 61  49  49]]

 [[ 73  63  61]
  [ 81  71  69]
  [ 84  73  71]
  ..., 
  [ 66  55  53]
  [ 61  49  49]
  [ 57  45  45]]

 [[ 74  64  62]
  [ 80  70  68]
  [ 78  67  65]
  ..., 
  [ 67  55  55]
  [ 62  50  50]
  [ 60  48  48]]]
[[[ 76  61  54]
  [ 73  58  53]
  [ 70  57  51]
  ..., 
  [132 128 116]
  [135 129 117]
  [135 129 117]]

 [[ 77  64  56]
  [ 76  63  57]
  [ 73  60  54]
  ..., 
  [133 129 117]
  [135 129 117]
  [136 130 118]]

 [[ 80  67  59]
  [ 78  67  61]
  [ 76  65  59]
  ..., 
  [133 129 117]
  [135 129 117]
  [136 130 118]]

 ..., 
 [[155 130  99]
  [155 130  99]


[[[253 253 253]
  [254 254 254]
  [254 254 254]
  ..., 
  [245 245 245]
  [245 245 245]
  [246 246 246]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ..., 
  [245 245 245]
  [247 247 247]
  [248 248 248]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ..., 
  [246 246 246]
  [247 247 247]
  [249 249 249]]

 ..., 
 [[ 58  58  58]
  [ 63  63  63]
  [ 64  64  64]
  ..., 
  [255 255 255]
  [213 213 213]
  [ 94  94  94]]

 [[ 69  69  69]
  [ 67  67  67]
  [ 60  60  60]
  ..., 
  [254 254 254]
  [205 205 205]
  [ 91  91  91]]

 [[ 80  80  80]
  [ 81  81  81]
  [ 75  75  75]
  ..., 
  [255 255 255]
  [178 178 178]
  [ 81  81  81]]]
[[[ 19  19  19]
  [ 23  23  23]
  [ 14  14  14]
  ..., 
  [ 33  33  33]
  [ 37  37  37]
  [ 41  41  41]]

 [[ 19  19  19]
  [ 39  39  39]
  [ 21  21  21]
  ..., 
  [ 34  34  34]
  [ 42  42  42]
  [ 41  41  41]]

 [[ 24  24  24]
  [ 37  37  37]
  [ 19  19  19]
  ..., 
  [ 36  36  36]
  [ 47  47  47]
  [ 45  45  45]]

 ..., 
 [[128 128 128]
  [127 127 127]


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[177 198 193]
  [170 189 183]
  [152 167 162]
  ..., 
  [164 180 177]
  [160 179 175]
  [162 178 175]]

 [[179 198 192]
  [162 181 175]
  [151 166 161]
  ..., 
  [169 179 178]
  [161 176 173]
  [154 173 171]]

 [[185 201 198]
  [159 179 178]
  [138 158 159]
  ..., 
  [165 179 179]
  [166 178 174]
  [153 169 166]]]
[[[109 160 145]
  [108 158 146]
  [108 158 149]
  ..., 
  [ 53 105  67]
  [ 56 108  69]
  [ 69 122  80]]

 [[105 156 141]
  [ 98 148 136]
  [ 94 144 133]
  ..., 
  [ 37  91  55]
  [ 40  92  54]
  [ 60 112  74]]

 [[112 163 148]
  [ 84 134 122]
  [ 81 131 119]
  ..., 
  [ 45  99  65]
  [ 46 100  68]
  [ 76 127  96]]

 ..., 
 [[119 131 127]
  [111 123 119]


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[156 151 145]
  [126 122 123]
  [179 172 179]
  ..., 
  [253 254 248]
  [254 253 248]
  [254 253 248]]

 [[233 230 215]
  [152 143 136]
  [182 168 168]
  ..., 
  [253 254 248]
  [254 253 248]
  [254 253 248]]

 [[134 143 114]
  [103 104  88]
  [193 188 185]
  ..., 
  [253 254 248]
  [253 254 248]
  [254 253 248]]

 ..., 
 [[216 210 244]
  [210 209 241]
  [212 211 245]
  ..., 
  [186 184 197]
  [193 186 204]
  [186 176 200]]

 [[216 210 244]
  [213 212 244]
  [208 207 241]
  ..., 
  [184 182 195]
  [191 184 202]
  [185 176 197]]

 [[214 207 241]
  [214 213 245]
  [2

[[[179  29  54]
  [164  25  46]
  [144  22  37]
  ..., 
  [150 132 122]
  [154 136 126]
  [157 139 129]]

 [[175  21  45]
  [167  21  44]
  [149  20  38]
  ..., 
  [152 135 127]
  [154 137 129]
  [156 139 131]]

 [[181  18  45]
  [176  22  46]
  [164  22  44]
  ..., 
  [152 134 130]
  [150 132 128]
  [149 131 127]]

 ..., 
 [[ 76  52  48]
  [ 76  46  44]
  [ 64  22  24]
  ..., 
  [117 109  98]
  [153 145 134]
  [177 169 158]]

 [[ 84  83  88]
  [ 54  52  57]
  [  4   0   2]
  ..., 
  [140 130 120]
  [174 164 154]
  [164 154 144]]

 [[192 191 196]
  [146 144 149]
  [ 70  64  68]
  ..., 
  [140 130 120]
  [170 160 150]
  [157 147 137]]]
[[[ 58  51  33]
  [ 59  52  36]
  [ 57  51  37]
  ..., 
  [ 64  55  40]
  [ 68  56  42]
  [ 67  53  40]]

 [[ 56  53  36]
  [ 58  50  37]
  [ 64  52  40]
  ..., 
  [ 63  56  40]
  [ 65  58  42]
  [ 65  56  41]]

 [[ 59  49  37]
  [ 58  50  37]
  [ 61  55  43]
  ..., 
  [ 64  58  44]
  [ 66  60  46]
  [ 65  59  45]]

 ..., 
 [[ 47  37  35]
  [ 46  47  39]


[[[ 94 104  96]
  [ 91  96  90]
  [ 99 101  96]
  ..., 
  [123 108 101]
  [125 108 100]
  [118 111 105]]

 [[ 97 104  97]
  [ 91  96  90]
  [ 98 100  95]
  ..., 
  [124 109 102]
  [126 109 101]
  [120 113 107]]

 [[ 98 105  98]
  [ 90  95  89]
  [ 96  97  92]
  ..., 
  [125 110 103]
  [128 111 103]
  [121 114 108]]

 ..., 
 [[ 17   2   9]
  [ 13   1   5]
  [ 14   2   6]
  ..., 
  [232 232 240]
  [229 232 239]
  [234 229 233]]

 [[ 21   6  13]
  [ 15   3   7]
  [ 15   3   7]
  ..., 
  [231 234 241]
  [231 234 241]
  [240 235 239]]

 [[ 26  11  18]
  [ 18   6  10]
  [ 16   4   8]
  ..., 
  [227 230 237]
  [229 232 241]
  [237 233 234]]]
[[[202 231 247]
  [205 237 252]
  [203 236 251]
  ..., 
  [ 34  62  48]
  [ 31  59  45]
  [ 35  63  49]]

 [[182 217 245]
  [188 223 251]
  [186 223 250]
  ..., 
  [ 26  53  38]
  [ 22  49  32]
  [ 27  54  37]]

 [[181 223 248]
  [185 229 254]
  [183 229 253]
  ..., 
  [ 27  54  35]
  [ 22  49  30]
  [ 28  55  36]]

 ..., 
 [[ 55 107  32]
  [ 66 121  40]


[[[223 223 231]
  [224 224 232]
  [222 225 232]
  ..., 
  [203 208 228]
  [201 208 227]
  [201 207 229]]

 [[224 224 232]
  [225 225 233]
  [226 226 234]
  ..., 
  [203 210 229]
  [203 210 228]
  [202 209 228]]

 [[226 227 232]
  [226 227 232]
  [227 227 235]
  ..., 
  [205 212 231]
  [205 212 230]
  [205 212 230]]

 ..., 
 [[147 119 105]
  [145 116 102]
  [143 111 100]
  ..., 
  [106  73  66]
  [106  73  68]
  [107  76  71]]

 [[147 119 105]
  [145 116 102]
  [141 109  96]
  ..., 
  [106  73  64]
  [106  73  64]
  [108  78  70]]

 [[145 117 103]
  [144 115 101]
  [140 108  95]
  ..., 
  [106  73  64]
  [103  73  63]
  [106  76  68]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[4 4 4]
  [3 3 3]
  [6 6 6]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[3 3 3]
  [7 7 7]
  [6 6 6]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]



[[[112  36  20]
  [116  40  26]
  [116  40  26]
  ..., 
  [145  67  21]
  [148  69  28]
  [146  66  29]]

 [[119  43  27]
  [111  35  21]
  [113  37  23]
  ..., 
  [149  70  29]
  [154  72  34]
  [153  71  34]]

 [[111  39  17]
  [115  42  23]
  [115  42  23]
  ..., 
  [146  63  29]
  [148  65  31]
  [150  68  31]]

 ..., 
 [[106  40  24]
  [104  35  19]
  [112  41  23]
  ..., 
  [ 22  18  17]
  [ 25  19  19]
  [ 27  22  19]]

 [[108  42  26]
  [106  37  22]
  [113  41  26]
  ..., 
  [ 19  15  14]
  [ 21  17  16]
  [ 25  20  17]]

 [[105  38  21]
  [106  36  24]
  [115  41  28]
  ..., 
  [ 16  15  13]
  [ 20  16  15]
  [ 24  19  16]]]
[[[157 120  67]
  [159 117  69]
  [154 117  65]
  ..., 
  [ 21  24  29]
  [ 23  24  29]
  [ 23  24  29]]

 [[164 117  71]
  [146 123  71]
  [156 120  70]
  ..., 
  [ 22  25  30]
  [ 23  24  29]
  [ 24  25  30]]

 [[135 118  64]
  [159 116  71]
  [152 120  69]
  ..., 
  [ 23  24  28]
  [ 22  23  27]
  [ 23  22  27]]

 ..., 
 [[ 22  21  19]
  [ 31  30  26]


[[[245 248 239]
  [247 250 243]
  [247 248 243]
  ..., 
  [252 254 241]
  [253 255 242]
  [253 255 242]]

 [[246 248 237]
  [246 247 239]
  [245 246 240]
  ..., 
  [252 254 241]
  [252 254 241]
  [253 255 242]]

 [[245 247 234]
  [245 247 236]
  [246 247 239]
  ..., 
  [252 254 241]
  [252 254 241]
  [252 254 241]]

 ..., 
 [[122 114  75]
  [117 113  84]
  [121 114  86]
  ..., 
  [117 119  80]
  [123 125  85]
  [136 137  93]]

 [[120 114  78]
  [118 114  87]
  [121 114  86]
  ..., 
  [117 119  82]
  [123 123  87]
  [133 131  92]]

 [[121 115  79]
  [116 115  87]
  [119 114  84]
  ..., 
  [120 122  85]
  [125 125  89]
  [132 130  92]]]
[[[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ..., 
  [18 18 18]
  [17 17 17]
  [17 17 17]]

 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ..., 
  [18 18 18]
  [17 17 17]
  [17 17 17]]

 [[ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]
  ..., 
  [18 18 18]
  [18 18 18]
  [18 18 18]]

 ..., 
 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ..., 
  [ 4  4  4]
  [ 3  3  3]
  [ 3  3  3]]